import { describe, expect, it, vi } from 'vitest'
import { env, runInDurableObject } from 'cloudflare:test'
vi.mock('agents', () => ({
  getAgentByName: async () => ({}),
  Agent: class {},
  Connection: class {},
}))
import { SpaceDO } from '../../../space/src/space/durable-object'
import { readBlobBytes, walkTreeFiles } from '../../../space/src/space/git-objects'
import { FileManager } from '../services/implementations/FileManager'
import { ThinkCodingBehavior } from './behaviors/think'
import { WorkspaceStore } from '../../../sdk/src/workspace'
import type { BaseProjectState, FileState } from './state'
import type { Env } from '../../../space/src/env'
import type {} from '../../../space/test/test-env'

const paths = ['/index.html', '/a-only.txt', '/b-only.txt'] as const
const A = {
  '/index.html': 'RESTORE_REAL_A',
  '/a-only.txt': 'A_ONLY',
  '/b-only.txt': null,
} as const
const B = {
  '/index.html': 'RESTORE_REAL_B',
  '/a-only.txt': null,
  '/b-only.txt': 'B_ONLY',
} as const

type PersistedState = BaseProjectState & {
  generatedFilesMap: Record<string, FileState>
}

async function commit(space: SpaceDO, message: string): Promise<string> {
  await space.gitCommit(message)
  return (await space.gitLog(1))[0].oid
}

async function tree(space: SpaceDO, oid: string) {
  const fs = (space as any).backend.fs
  const entries = await walkTreeFiles(fs, oid)
  return Object.fromEntries(await Promise.all(paths.map(async (path) => {
    const entry = entries.get(path)
    return [path, entry ? new TextDecoder().decode(await readBlobBytes(fs, entry.oid)) : null]
  })))
}

async function createAB(space: SpaceDO) {
  await space.writeFile('/index.html', A['/index.html'])
  await space.writeFile('/a-only.txt', A['/a-only.txt'])
  const commitA = await commit(space, 'A')
  await space.writeFile('/index.html', B['/index.html'])
  await space.deleteFile('/a-only.txt')
  await space.writeFile('/b-only.txt', B['/b-only.txt'])
  await (space as any).backend.git.add({ filepath: 'index.html' })
  const commitB = await commit(space, 'B')
  expect(await tree(space, commitA)).toEqual(A)
  expect(await tree(space, commitB)).toEqual(B)
  return { commitA, commitB }
}

function stateWithB(): PersistedState {
  const file = (filePath: string, fileContents: string): FileState => ({
    filePath,
    fileContents,
    filePurpose: 'Generated by think',
    lastDiff: '',
  })
  return {
    behaviorType: 'think',
    projectType: 'app',
    projectName: 'restore-stale-state-test',
    query: 'restore stale state',
    generatedFilesMap: {
      'index.html': file('index.html', B['/index.html']),
      'b-only.txt': file('b-only.txt', B['/b-only.txt']!),
    },
  } as PersistedState
}

function behaviorForState(state: PersistedState, space: SpaceDO, broadcasts: unknown[] = []) {
  const behavior = Object.create(ThinkCodingBehavior.prototype) as ThinkCodingBehavior
  let current = state
  const stateManager = {
    getState: () => current,
    setState: (next: PersistedState) => { current = next },
    updateField: () => undefined,
  }
  const git = {
    setOnFilesChangedCallback: () => undefined,
    getAllFilesFromHead: async () => [],
  }
  Object.defineProperty(behavior, 'state', {
    get: () => current,
    set: (next: PersistedState) => { current = next },
    configurable: true,
  })
  Object.defineProperty(behavior, 'setState', {
    value: (next: PersistedState) => { current = next },
    writable: true,
    configurable: true,
  })
  Object.defineProperty(behavior, 'fileManager', {
    value: new FileManager(
    stateManager,
    () => ({ allFiles: {}, dontTouchFiles: new Set<string>() } as any),
    git as any,
    ),
    writable: true,
    configurable: true,
  })
  // Exercise the actual ThinkCodingBehavior.rollbackToCommit entry point while
  // keeping the real SpaceDO in the Cloudflare test harness.
  Object.defineProperty(behavior, 'callSpace', {
    value: <T>(call: (target: any) => Promise<T>) => call(space),
    writable: true,
    configurable: true,
  })
  Object.defineProperty(behavior, 'broadcast', {
    value: (type: string, payload: unknown) => broadcasts.push({ type, payload }),
    writable: true,
    configurable: true,
  })
  Object.defineProperty(behavior, 'isCodeGenerating', {
    value: () => false,
    writable: true,
    configurable: true,
  })
  Object.defineProperty(behavior, 'infrastructure', {
    value: {
      logger: () => ({ warn: () => undefined, error: () => undefined }),
      setState: (next: PersistedState) => {
        current = next
        broadcasts.push({ type: 'cf_agent_state', state: next })
      },
    },
    configurable: true,
  })
  return { behavior, getState: () => current }
}

function projection(state: PersistedState) {
  return Object.fromEntries(
    Object.entries(state.generatedFilesMap).map(([path, file]) => [path, file.fileContents]),
  )
}

function assertAProjection(state: PersistedState) {
  expect(projection(state)).toEqual({
    'index.html': A['/index.html'],
    'a-only.txt': A['/a-only.txt'],
  })
  expect(state.generatedFilesMap['b-only.txt']).toBeUndefined()
}

function assertWorkspaceA(state: PersistedState) {
  const workspace = new WorkspaceStore()
  workspace.applyWsMessage({ type: 'agent_connected', state } as any)
  expect(workspace.snapshot()).toEqual({
    'index.html': A['/index.html'],
    'a-only.txt': A['/a-only.txt'],
  })
  expect(workspace.read('b-only.txt')).toBeNull()
  return workspace
}

describe('ThinkAgent state after an authoritative SpaceDO restore', () => {
  it('refreshes the current session projection to complete A after restore', async () => {
    const stub = env.FsHarnessDO.get(env.FsHarnessDO.idFromName('think-stale-current'))
    await runInDurableObject(stub, async (_instance, state) => {
      const space = new SpaceDO(state, {} as Env)
      const { commitA } = await createAB(space)
      ;(space as any).deploy = async () => ({ error: 'test deploy unavailable' })
      const broadcasts: unknown[] = []
      const { behavior } = behaviorForState(stateWithB(), space, broadcasts)
      await behavior.rollbackToCommit(commitA)
      const forward = (await space.gitLog(1))[0].oid
      expect(await tree(space, forward)).toEqual(A)

      const files = await behavior.readFiles(['index.html', 'a-only.txt', 'b-only.txt'])
      expect(broadcasts).toEqual(expect.arrayContaining([
        expect.objectContaining({ type: 'deployment_failed' }),
      ]))
      assertAProjection(behavior.state as PersistedState)
      expect(files.files).toEqual([
        { path: 'index.html', content: A['/index.html'] },
        { path: 'a-only.txt', content: A['/a-only.txt'] },
      ])
      assertWorkspaceA(behavior.state as PersistedState)
    })
  })

  it('rehydrates complete A, including deletion, after a fresh reconnect', async () => {
    const stub = env.FsHarnessDO.get(env.FsHarnessDO.idFromName('think-stale-reconnect'))
    await runInDurableObject(stub, async (_instance, state) => {
      const space = new SpaceDO(state, {} as Env)
      const { commitA } = await createAB(space)
      ;(space as any).deploy = async () => ({ error: 'test deploy unavailable' })
      const broadcasts: unknown[] = []
      const currentSession = behaviorForState(stateWithB(), space, broadcasts)
      await currentSession.behavior.rollbackToCommit(commitA)
      const forward = (await space.gitLog(1))[0].oid
      expect(await tree(space, forward)).toEqual(A)

      // A fresh ticketed reconnect rehydrates the serialized Think state; it
      // does not reconstruct files from SpaceDO.
      const persisted = JSON.parse(JSON.stringify(currentSession.getState())) as PersistedState
      const reconnected = behaviorForState(persisted, space).behavior
      const snapshot = reconnected.listFiles()
      const files = await reconnected.readFiles(['index.html', 'a-only.txt', 'b-only.txt'])
      assertAProjection(currentSession.getState())
      expect(Object.fromEntries(snapshot.map((file) => [file.filePath, file.fileContents]))).toEqual({
        'index.html': A['/index.html'],
        'a-only.txt': A['/a-only.txt'],
      })
      expect(snapshot.some((file) => file.filePath === 'b-only.txt')).toBe(false)
      expect(files.files).toEqual([
        { path: 'index.html', content: A['/index.html'] },
        { path: 'a-only.txt', content: A['/a-only.txt'] },
      ])
      assertWorkspaceA(persisted)
    })
  })

  it('starts the representative next edit from the refreshed A host read', async () => {
    const stub = env.FsHarnessDO.get(env.FsHarnessDO.idFromName('think-stale-next-edit'))
    await runInDurableObject(stub, async (_instance, state) => {
      const space = new SpaceDO(state, {} as Env)
      const { commitA } = await createAB(space)
      ;(space as any).deploy = async () => ({ error: 'test deploy unavailable' })
      const { behavior } = behaviorForState(stateWithB(), space)
      await behavior.rollbackToCommit(commitA)
      const forward = (await space.gitLog(1))[0].oid
      expect(await tree(space, forward)).toEqual(A)

      const beforeEdit = await behavior.readFiles(['index.html'])
      const nextContent = `${beforeEdit.files[0].content}\nEDIT_AFTER_RESTORE`
      await (behavior as any).callSpace((target: SpaceDO) => target.writeFile('/index.html', nextContent))
      await (space as any).backend.git.add({ filepath: 'index.html' })
      const nextCommit = await commit(space, 'next edit after restore')
      expect((await tree(space, nextCommit))['/index.html'])
        .toBe(`${A['/index.html']}\nEDIT_AFTER_RESTORE`)
    })
  })

  it('fails closed when authoritative projection refresh fails', async () => {
    const stub = env.FsHarnessDO.get(env.FsHarnessDO.idFromName('think-stale-refresh-failure'))
    await runInDurableObject(stub, async (_instance, state) => {
      const space = new SpaceDO(state, {} as Env)
      const { commitA } = await createAB(space)
      ;(space as any).deploy = async () => ({ commit_hash: 'should-not-deploy' })
      const broadcasts: unknown[] = []
      const current = behaviorForState(stateWithB(), space, broadcasts)
      ;(space as any).glob = async () => { throw new Error('injected refresh failure') }
      await current.behavior.rollbackToCommit(commitA)

      expect(await tree(space, (await space.gitLog(1))[0].oid)).toEqual(A)
      expect(broadcasts).toEqual(expect.arrayContaining([
        expect.objectContaining({
          type: 'deployment_failed',
          payload: expect.objectContaining({ error: expect.stringContaining('session file refresh failed') }),
        }),
      ]))
      expect(broadcasts.some((event: any) => event.type === 'deployment_completed')).toBe(false)
      expect(broadcasts.some((event: any) => event.type === 'conversation_response')).toBe(false)
      expect(projection(current.getState())).toEqual({})
      expect(current.getState().generatedFilesMap['b-only.txt']).toBeUndefined()
    })
  })

  it('does not report success when publishing the restored projection fails', async () => {
    const stub = env.FsHarnessDO.get(env.FsHarnessDO.idFromName('think-stale-publish-failure'))
    await runInDurableObject(stub, async (_instance, state) => {
      const space = new SpaceDO(state, {} as Env)
      const { commitA } = await createAB(space)
      ;(space as any).deploy = async () => ({ commit_hash: 'restored-a' })
      const broadcasts: unknown[] = []
      const current = behaviorForState(stateWithB(), space, broadcasts)
      const infrastructure = (current.behavior as any).infrastructure
      const publish = infrastructure.setState
      let failOnce = true
      infrastructure.setState = (next: PersistedState) => {
        if (failOnce) {
          failOnce = false
          throw new Error('injected state persistence failure')
        }
        publish(next)
      }
      await current.behavior.rollbackToCommit(commitA)

      expect(await tree(space, (await space.gitLog(1))[0].oid)).toEqual(A)
      expect(projection(current.getState())).toEqual({})
      expect(broadcasts).toEqual(expect.arrayContaining([
        expect.objectContaining({
          type: 'deployment_failed',
          payload: expect.objectContaining({ error: expect.stringContaining('state persistence failure') }),
        }),
      ]))
      expect(broadcasts.some((event: any) => event.type === 'deployment_completed')).toBe(false)
      expect(broadcasts.some((event: any) => event.type === 'conversation_response')).toBe(false)
    })
  })

  it('refreshes A before reporting a successful restore', async () => {
    const stub = env.FsHarnessDO.get(env.FsHarnessDO.idFromName('think-stale-success-boundary'))
    await runInDurableObject(stub, async (_instance, state) => {
      const space = new SpaceDO(state, {} as Env)
      const { commitA } = await createAB(space)
      ;(space as any).deploy = async () => ({ commit_hash: 'restored-a' })
      const broadcasts: unknown[] = []
      const current = behaviorForState(stateWithB(), space, broadcasts)
      Object.defineProperty(current.behavior, 'getBrowserPreviewURL', {
        value: async () => 'https://preview.example.test',
        configurable: true,
      })
      await current.behavior.rollbackToCommit(commitA)

      const completed = broadcasts.find((event: any) => event.type === 'deployment_completed') as any
      expect(completed).toBeDefined()
      expect(projection(current.getState())).toEqual({
        'index.html': A['/index.html'],
        'a-only.txt': A['/a-only.txt'],
      })
      expect(completed.payload).toEqual({ previewURL: 'https://preview.example.test' })
      expect(broadcasts.findIndex((event: any) => event.type === 'deployment_completed'))
        .toBeLessThan(broadcasts.findIndex((event: any) => event.type === 'conversation_response'))
    })
  })

  it('refreshes A when preview deployment throws after the forward commit', async () => {
    const stub = env.FsHarnessDO.get(env.FsHarnessDO.idFromName('think-stale-deploy-throw'))
    await runInDurableObject(stub, async (_instance, state) => {
      const space = new SpaceDO(state, {} as Env)
      const { commitA } = await createAB(space)
      ;(space as any).deploy = async () => { throw new Error('injected preview failure') }
      const broadcasts: unknown[] = []
      const current = behaviorForState(stateWithB(), space, broadcasts)
      await current.behavior.rollbackToCommit(commitA)

      expect(await tree(space, (await space.gitLog(1))[0].oid)).toEqual(A)
      assertAProjection(current.getState())
      expect(broadcasts.some((event: any) => event.type === 'conversation_response')).toBe(false)
      expect(broadcasts).toEqual(expect.arrayContaining([
        expect.objectContaining({ type: 'deployment_failed' }),
      ]))
    })
  })
})